version: "3"
services:
  db:
    image: mysql
    container_name: mysql_tsoa
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Seoul"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_PORT}:3306
